name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Pac-Man graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Cipher1712
          output: pacman.svg   # IMPORTANT: single output file

      - name: Move output to dist folder
        run: |
          mkdir -p dist
          mv pacman.svg dist/pacman-contribution-graph.svg

      - name: Commit Pac-Man graph to output branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate Pac-Man Graph"
          branch: output
          file_pattern: dist/pacman-contribution-graph.svg
