name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:

jobs:
  pacman:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Pac-Man contribution graph
        uses: Platane/Pacman@main
        with:
          github_user_name: Cipher1712
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
          theme: "dark"

      - name: Commit Pac-Man graph to output branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Generate Pac-Man Graph"
          branch: output
          file_pattern: dist/*.svg
